import type ROUTEMAP from "@backend/routes/ROUTEMAP";

export default {
  uploads: {
    root: "/uploads",
    images: "/images",
    pdf: "/pdf",
    cv: "/cv",
  },
  users: {
    _params: { id: ":id" },
    root: "/users",
    get: "/",
    self: "/self",
    getById: "/:id",
    userLogout: "/logout",
    userLogin: "/login",
    userRegister: "/register",
    put: "/:id",
    delete: "/:id",
  },
  jobs: {
    _params: { id: ":id", hrId: ":hrId" },
    root: "/jobs",
    get: "/",
    getById: "/:id",
    getPublic: "/public",
    getPublicById: "/public/:id",
    getByHr: "/hr/:hrId",
    post: "/",
    put: "/:id",
    delete: "/:id",
    close: "/:id/close",
  },
  applications: {
    _params: { id: ":id", jobId: ":jobId", candidateId: ":candidateId" },
    root: "/applications",
    get: "/",
    getById: "/:id",
    getByJob: "/job/:jobId",
    getByCandidate: "/candidate/:candidateId",
    post: "/",
    updateStatus: "/:id/status",
    addNotes: "/:id/notes",
    delete: "/:id",
  },
  interviews: {
    _params: {
      id: ":id",
      jobId: ":jobId",
      candidateId: ":candidateId",
      applicationId: ":applicationId",
    },
    root: "/interviews",
    get: "/",
    getById: "/:id",
    getByJob: "/job/:jobId",
    getByCandidate: "/candidate/:candidateId",
    getByApplication: "/application/:applicationId",
    post: "/",
    bulkSchedule: "/bulk-schedule",
    put: "/:id",
    updateStatus: "/:id/status",
    addPreparationNotes: "/:id/preparation-notes",
    addFeedback: "/:id/feedback",
    delete: "/:id",
  },
  notifications: {
    _params: { id: ":id" },
    root: "/notifications",
    get: "/",
    getById: "/:id",
    getUnread: "/unread",
    markAsRead: "/:id/read",
    markAllAsRead: "/read-all",
    delete: "/:id",
  },
  admin: {
    _params: { hrId: ":hrId" },
    root: "/admin",
    dashboard: "/dashboard",
    createHr: "/hr",
    getHrUsers: "/hr",
    getHrById: "/hr/:hrId",
    updateHr: "/hr/:hrId",
    deleteHr: "/hr/:hrId",
    getAllJobs: "/jobs",
    getAllCandidates: "/candidates",
  },

  ai: {
    root: "/ai",
    chat: "/chat",
    generateDesc: "/generate-description",
    rankCandidates: "/rank-candidates",
    matchJobs: "/match-jobs",
  },

  calendar: {
    root: "/calendar",
    authUrl: "/auth-url",
    callBack: "/oauth/callback",
    status: "/status",
    embedURL: "/embed-url",
  },
} as const satisfies typeof ROUTEMAP;
